### ISSUE TITLE
Find API to Implement

### ISSUE THREAD

**Issue by thucchi-cs** [thucchi-cs/TSA#2]
Find a suitable API to implement in the website. Ideas for API:
- Carbon emissions based on location
- Tax benefits based on state
- Solar Panel Cost based on location

**Comment by thucchi-cs** [comment]
Carbon Intensity API of ElectricityMap has an error with the url. What is curl?? Url is broken into 2 parts like the attached pic
![image](https://github.com/thucchi-cs/TSA/assets/146598322/ef8c1f9b-adb3-438b-843a-348c4f85e069)

**Comment by Ronin-the-Barbarian** [comment]
Ok got a bit carried away but this works. Just translate it into javascript and stuff
`response = requests.get("https://api.electricitymap.org/v3/carbon-intensity/latest?zone="+zone,headers={'auth-token':'YZA4d9W0Mqwso'}) 
`
`response2 = requests.get("https://api.electricitymap.org/v3/zones").json()
`
`print(response.json())`

**Comment by thucchi-cs** [comment]
Thanks bud
